# Generated by Django 2.2.5 on 2019-09-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='matches.Location'),
        ),
        migrations.AlterField(
            model_name='employermatch',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.Employer'),
        ),
        migrations.AlterField(
            model_name='employermatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AlterField(
            model_name='locationmatch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.Location'),
        ),
        migrations.AlterField(
            model_name='locationmatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
        migrations.AlterField(
            model_name='match',
            name='user_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_user_a', to='users.User'),
        ),
        migrations.AlterField(
            model_name='match',
            name='user_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_user_b', to='users.User'),
        ),
        migrations.AlterField(
            model_name='positionmatch',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.Job'),
        ),
        migrations.AlterField(
            model_name='positionmatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
    ]
