# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=300, unique=True),
        ),
    ]
