# Generated by Django 2.2.5 on 2020-11-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_auto_20201118_1113'),
        ('questions', '0009_auto_20201118_1113'),
        ('matches', '0003_auto_20201118_1113'),
        ('users', '0002_auto_20190923_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
