# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', unique=True),
        ),
    ]
