# Generated by Django 2.2.5 on 2019-09-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20190923_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='my_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_answer', to='questions.Answer'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='my_answer_importance',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Very Important', 'Very Important'), ('Somewhat Important', 'Somewhat Important'), ('Not Important', 'Not Important')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='their_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_answer', to='questions.Answer'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='their_importance',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Very Important', 'Very Important'), ('Somewhat Important', 'Somewhat Important'), ('Not Important', 'Not Important')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User'),
        ),
    ]
