# Generated by Django 2.2.5 on 2019-09-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190923_1217'),
        ('questions', '0007_auto_20190923_1512'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question')},
        ),
    ]
