# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-04 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', jsonfield.fields.JSONField()),
                ('remove', jsonfield.fields.JSONField()),
                ('liked_users', models.ManyToManyField(blank=True, related_name='liked_users', to='users.User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.User')),
            ],
        ),
    ]
