# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='add',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userlike',
            name='remove',
            field=models.TextField(null=True),
        ),
    ]
