# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-27 10:58
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20190826_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='add',
            field=jsonfield.fields.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlike',
            name='remove',
            field=jsonfield.fields.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
