# Generated by Django 2.2.5 on 2019-09-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20190923_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='users.User'),
        ),
    ]
